# Generated by Django 4.2.4 on 2024-04-15 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theaters",
            name="movies",
        ),
    ]
